# NumPy Arrays

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3] # list

In [3]:
np.array(mylist) # numpy array

array([1, 2, 3])

In [4]:
nested_list = [[1,2],[3,4],[5,6]]

In [5]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.linspace(0,10,3) # 0 to 10 three evenly spaced numbers

array([ 0.,  5., 10.])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.eye(5) # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(2) # 2 random number generator

array([0.23569787, 0.00946235])

In [14]:
np.random.rand(3,4) # uniform distribution

array([[0.64740006, 0.30589056, 0.52814223, 0.70477053],
       [0.67229375, 0.79675633, 0.13212456, 0.57212658],
       [0.85426704, 0.17631323, 0.31186572, 0.36180152]])

In [15]:
np.random.randn(5) # mean 0, variance 1

array([-0.08675275, -0.68160782, -0.19353084,  1.41030373, -0.10030325])

In [16]:
np.random.randint(1,10) # generate random integer

1

In [17]:
np.random.randint(1,100,(2,3))

array([[23, 83,  7],
       [44, 26, 54]])

In [18]:
np.random.seed(42) # seed will generate same random numbers everytime
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [19]:
ranarr = np.random.randint(0,50,10)

In [20]:
arr = np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [23]:
arr.shape

(25,)

In [24]:
ranarr.shape

(10,)

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr.reshape(2,5)

array([[38, 18, 22, 10, 10],
       [23, 35, 39, 23,  2]])

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr.max()

39

In [29]:
ranarr.min() # minimum value

2

In [30]:
ranarr.min() # maximum value

2

In [31]:
ranarr.argmax() # index of max value

7

In [32]:
ranarr.argmin() # index of min value

9

In [33]:
ranarr.dtype

dtype('int64')

# NumPy Operations

In [35]:
arr = np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[8]

8

In [38]:
arr[1:5]

array([1, 2, 3, 4])

In [39]:
arr[:5]

array([0, 1, 2, 3, 4])

In [40]:
arr[6:-1]

array([6, 7, 8, 9])

In [41]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [42]:
arr[0:5] = 100

In [43]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
arr = np.arange(0,11)

In [45]:
slice_of_arr = arr[0:5]

In [46]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [47]:
slice_of_arr[:] = 99 # it is just a pointer to arr

In [48]:
slice_of_arr 

array([99, 99, 99, 99, 99])

In [49]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [50]:
arr_copy = arr.copy()

In [51]:
arr_copy[:] = 100

In [52]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [53]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [54]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [55]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
arr_2d.shape

(3, 3)

In [59]:
arr_2d[:][1]

array([20, 25, 30])

In [60]:
arr_2d[1][:]

array([20, 25, 30])

In [62]:
arr_2d[1][2]

30

In [65]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [66]:
arr = np.arange(1,11)

In [67]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [69]:
bool_arr = arr>4

In [70]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [71]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [72]:
new_arr = np.random.randn(5)

In [73]:
new_arr

array([-0.46947439,  0.54256004, -0.46341769, -0.46572975,  0.24196227])

In [74]:
bool_arr = new_arr > 0

In [75]:
bool_arr

array([False,  True, False, False,  True])

In [76]:
new_arr[bool_arr]

array([0.54256004, 0.24196227])

In [77]:
new_arr[new_arr>0]

array([0.54256004, 0.24196227])

# NumPy Operations

In [78]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [80]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [81]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [82]:
arr / 0

/home/vboxuser/anaconda3/envs/tf2/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [83]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [84]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [85]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [86]:
arr.sum()

55

In [87]:
arr.mean()

5.5

In [88]:
arr.max()

10

In [89]:
arr.var()

8.25

In [90]:
arr.std()

2.8722813232690143

In [91]:
arr2d = np.arange(0,25).reshape(5,5)

In [92]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [93]:
arr2d.sum()

300

In [94]:
arr2d.sum(axis=0) # sum by column

array([50, 55, 60, 65, 70])

In [95]:
arr2d.sum(axis=1) # sum by rows

array([ 10,  35,  60,  85, 110])