# Lecture 1

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3] # list

In [3]:
np.array(mylist) # numpy array

array([1, 2, 3])

In [5]:
nested_list = [[1,2],[3,4],[5,6]]

In [6]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,3) # 0 to 10 three evenly spaced numbers

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.eye(5) # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(2) # 2 random number generator

array([0.75157647, 0.78785189])

In [16]:
np.random.rand(3,4) # uniform distribution

array([[0.3982736 , 0.66902914, 0.92789764, 0.36713947],
       [0.9650586 , 0.24846763, 0.0304735 , 0.73028643],
       [0.15559726, 0.85838365, 0.40016677, 0.63448845]])

In [20]:
np.random.randn(5) # mean 0, variance 1

array([ 0.69669468,  0.14645454,  1.16846776, -0.01814219,  0.13384534])

In [22]:
np.random.randint(1,10) # generate random integer

1

In [23]:
np.random.randint(1,100,(2,3))

array([[75, 95, 48],
       [39,  3, 16]])

In [25]:
np.random.seed(42) # seed will generate same random numbers everytime
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [26]:
ranarr = np.random.randint(0,50,10)

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [30]:
arr.shape

(25,)

In [31]:
ranarr.shape

(10,)

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ranarr.reshape(2,5)

array([[38, 18, 22, 10, 10],
       [23, 35, 39, 23,  2]])

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr.max()

39

In [42]:
ranarr.min() # minimum value

2

In [43]:
ranarr.min() # maximum value

2

In [44]:
ranarr.argmax() # index of max value

7

In [46]:
ranarr.argmin() # indes of min value

9

In [47]:
ranarr.dtype

dtype('int64')