# The Data

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [8]:
import tensorflow as tf

In [9]:
path_to_file = "shakespeare.txt"

In [10]:
text = open(path_to_file,'r').read()

In [11]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [12]:
print(text[40500:41000])

umbers should be broken,
  While shadows like to thee do mock my sight?
  Is it thy spirit that thou send'st from thee
  So far from home into my deeds to pry,
  To find out shames and idle hours in me,
  The scope and tenure of thy jealousy?
  O no, thy love though much, is not so great,
  It is my love that keeps mine eye awake,
  Mine own true love that doth my rest defeat,
  To play the watchman ever for thy sake.
    For thee watch I, whilst thou dost wake elsewhere,
    From me far off, wi


# Text Processing

In [13]:
vocab = sorted(set(text))

In [14]:
len(vocab)

84

In [15]:
for pair in enumerate(vocab):
    print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [16]:
char_to_ind = {char:ind for ind,char in enumerate(vocab)}

In [17]:
char_to_ind['H']

33

In [18]:
ind_to_char = np.array(vocab)

In [19]:
ind_to_char[33]

'H'

In [20]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [21]:
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29])

In [22]:
encoded_text.shape

(5445609,)

In [23]:
sample = text[:500]

In [24]:
sample

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [25]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

# Creating Batches

In [26]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [27]:
line = 'From fairest creatures we desire increase'

In [28]:
len(line)

41

In [29]:
lines = '''
From fairest creatures we desire increase,
That thereby beauty's rose might never die,
But as the riper should by time decease,
'''

In [30]:
len(lines)

129

In [31]:
seq_len = 120

In [32]:
total_num_seq = len(text) // (seq_len + 1)

In [33]:
total_num_seq

45005

In [34]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [35]:
type(char_dataset)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [36]:
for item in char_dataset.take(500):
    print(ind_to_char[item.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


In [37]:
sequences = char_dataset.batch(seq_len + 1,drop_remainder=True)

In [38]:
def create_seq_targets(seq):
    input_txt = seq[:-1] # Hello my nam
    target_txt = seq[1:] # ello my name
    return input_txt,target_txt

In [39]:
dataset = sequences.map(create_seq_targets)

In [40]:
for input_txt,target_txt in dataset.take(1):
    print(input_txt.numpy())
    print("".join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    print("".join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [41]:
batch_size = 128

In [42]:
buffer_size = 10000
dataset = dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True)

In [43]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

# Creating the Model

In [44]:
vocab_size = len(vocab)

In [45]:
vocab_size

84

In [46]:
embed_dim = 64

In [47]:
rnn_neurons = 1026

In [48]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [49]:
def sparse_cat_loss(y_true,y_pred):
    return sparse_categorical_crossentropy(y_true,y_pred,from_logits=True)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,GRU,Dense

In [51]:
def create_model(vocab_size,embed_dim,rnn_neurons,batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size,embed_dim,batch_input_shape=[batch_size,None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    
    model.add(Dense(vocab_size))
    model.compile('adam',loss=sparse_cat_loss)
    
    return model

In [52]:
model = create_model(vocab_size,embed_dim=embed_dim,rnn_neurons=rnn_neurons,batch_size=batch_size)

In [53]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (128, None, 64)           5376      
                                                                 
 gru (GRU)                   (128, None, 1026)         3361176   
                                                                 
 dense (Dense)               (128, None, 84)           86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


# Training the model

In [54]:
for input_example_batch,target_example_batch in dataset.take(1):
  example_batch_predictions = model(input_example_batch)

In [55]:
example_batch_predictions.shape

TensorShape([128, 120, 84])

In [56]:
example_batch_predictions[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[-1.9515733e-03,  2.3139019e-03, -2.0812419e-03, ...,
        -5.8573782e-03, -3.7908696e-03, -1.5943255e-03],
       [ 3.7068408e-03,  5.5112923e-03,  7.8158779e-03, ...,
        -1.4683787e-03, -4.8465845e-03,  7.7326223e-03],
       [ 2.4731923e-04,  5.5666431e-03,  7.3474360e-04, ...,
        -7.1350764e-03, -5.1453095e-03,  3.1248040e-03],
       ...,
       [-6.6426536e-04, -1.9300927e-05, -4.9441941e-03, ...,
         7.9999724e-03, -4.3045217e-03,  3.3199941e-03],
       [ 8.9982973e-04, -4.5494032e-03, -3.5142326e-03, ...,
         1.1516819e-02, -5.6226244e-03, -4.9434191e-05],
       [ 4.1756155e-03,  5.3401798e-04, -4.3175598e-03, ...,
         1.0819666e-02, -9.0715969e-03, -4.1800332e-03]], dtype=float32)>

In [57]:
sampled_indices = tf.random.categorical(example_batch_predictions[0],num_samples = 1)

In [58]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[38],
       [81],
       [59],
       [54],
       [22],
       [39],
       [ 4],
       [29],
       [49],
       [60],
       [45],
       [11],
       [49],
       [25],
       [57],
       [76],
       [ 4],
       [76],
       [ 5],
       [ 3],
       [ 2],
       [ 7],
       [19],
       [ 3],
       [ 3],
       [43],
       [40],
       [12],
       [78],
       [ 8],
       [49],
       [76],
       [66],
       [58],
       [63],
       [69],
       [75],
       [17],
       [11],
       [73],
       [63],
       [48],
       [60],
       [47],
       [62],
       [12],
       [81],
       [73],
       [73],
       [49],
       [11],
       [67],
       [76],
       [76],
       [10],
       [24],
       [26],
       [71],
       [19],
       [ 3],
       [11],
       [81],
       [14],
       [33],
       [26],
       [36],
       [11],
       [ 2],
       [68],
       [72],
       [ 3],
       [20],
       [46],
   

In [59]:
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [60]:
sampled_indices

array([38, 81, 59, 54, 22, 39,  4, 29, 49, 60, 45, 11, 49, 25, 57, 76,  4,
       76,  5,  3,  2,  7, 19,  3,  3, 43, 40, 12, 78,  8, 49, 76, 66, 58,
       63, 69, 75, 17, 11, 73, 63, 48, 60, 47, 62, 12, 81, 73, 73, 49, 11,
       67, 76, 76, 10, 24, 26, 71, 19,  3, 11, 81, 14, 33, 26, 36, 11,  2,
       68, 72,  3, 20, 46, 29, 42, 24, 75,  0, 21, 40, 34, 13, 66, 13, 74,
       49, 55, 51, 48, 45, 74, 18, 63, 80, 21, 73,  3, 43, 13, 67,  9, 78,
       51, 55, 57, 78, 69, 22, 11, 65, 45, 53, 43, 68, 83, 28, 43, 51, 11,
       25])

In [61]:
ind_to_char[sampled_indices] # random

array(['M', 'z', 'd', '_', ';', 'N', '&', 'D', 'X', 'e', 'T', '0', 'X',
       '?', 'b', 'u', '&', 'u', "'", '"', '!', ')', '8', '"', '"', 'R',
       'O', '1', 'w', ',', 'X', 'u', 'k', 'c', 'h', 'n', 't', '6', '0',
       'r', 'h', 'W', 'e', 'V', 'g', '1', 'z', 'r', 'r', 'X', '0', 'l',
       'u', 'u', '.', '>', 'A', 'p', '8', '"', '0', 'z', '3', 'H', 'A',
       'K', '0', '!', 'm', 'q', '"', '9', 'U', 'D', 'Q', '>', 't', '\n',
       ':', 'O', 'I', '2', 'k', '2', 's', 'X', '`', 'Z', 'W', 'T', 's',
       '7', 'h', 'y', ':', 'r', '"', 'R', '2', 'l', '-', 'w', 'Z', '`',
       'b', 'w', 'n', ';', '0', 'j', 'T', ']', 'R', 'm', '}', 'C', 'R',
       'Z', '0', '?'], dtype='<U1')

In [62]:
epochs = 30

In [64]:
# model.fit(dataset,epochs = epochs)

In [65]:
from tensorflow.keras.models import load_model

# Generating Text

In [67]:
model = create_model(vocab_size,embed_dim,rnn_neurons,batch_size=1)
model.load_weights('shakespeare_gen.h5')
model.build(tf.TensorShape([1,None]))

In [68]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (1, None, 64)             5376      
                                                                 
 gru_2 (GRU)                 (1, None, 1026)           3361176   
                                                                 
 dense_2 (Dense)             (1, None, 84)             86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [73]:
def generate_text(model,start_seed,gen_size=500,temp=1.0):

  num_generate = gen_size

  input_eval = [char_to_ind[s] for s in start_seed]

  input_eval = tf.expand_dims(input_eval,0)

  text_generated = []

  temperature = temp 

  model.reset_states()

  for i in range(num_generate):
    predictions = model(input_eval)
    predictions = tf.squeeze(predictions,0)
    predictions = predictions/temperature
    predicted_id = tf.random.categorical(predictions,num_samples = 1)[-1,0].numpy()
    input_eval = tf.expand_dims([predicted_id],0)
    text_generated.append(ind_to_char[predicted_id])

  return(start_seed + "".join(text_generated))

In [74]:
print(generate_text(model,"JULIET",gen_size=1000))

JULIETIXE.  PROJECT GUTENBERG ETEXT OF ILLINOIS BENEDICTINE COLLEGE
WITH PERMISSION.  ELECTRONIC AND MACHINE READABLE COPIES MAY BE
DISTRIBUTED SO LONG AS SUCH COPATI. We are both one, and do him nothing spring; their boots
    Do plumed as his father shined with
    my kinsmod?
    I should have haded the venier to be cruel.
  'Where be so long as that in yout his first,
    And the gods give our King; and then into a
    judgment.
  FALSTAFF. I have been can be repeas'd, and here is nothing.
  POMPEY. Sir, I love you with a most prince, Marshine her pageant comes!'
    'Tis pity you withal.
  IACHIMO. Fie, fie! what?
  BALCHAS. I think without mine else. Herald! 'st we now present
    Be of the hind'st conditions and well-favour'd faith!
    O Roman wife, beware yourself!
    I am no bloody, not a wife parted
    ging that she may; 'tis not a hair may kiss any way,
    And break friends.
  CAMILLO. He is, sir, 'tis most humble, and to read.
    Awake, again! away!
  LUCIO. I will go,